name: Generate ASCII Artwork
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cowsay
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay
        run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

      - name: Test File Existence
        run: grep -i "dragon" dragon.txt || echo "File not found"

      - name: Read File
        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls -ltra
